/**
 * TEST REPORTER
 * Generates technical and non-technical reports linking results to EP classifications.
 */

import fs from 'node:fs';
import path from 'node:path';
import type { TestResultRecord, TestRunSummary } from '../../interfaces/responses.js';

const REPORT_DIR = path.resolve(process.cwd(), '.reports');
const INTEGRATION_REPORT_FILE = path.join(REPORT_DIR, 'integration-report.md');
const INTEGRATION_SUMMARY_FILE = path.join(REPORT_DIR, 'integration-summary.md');
const INTEGRATION_JSON_FILE = path.join(REPORT_DIR, 'integration-results.json');

function ensureReportDir(): void {
  if (!fs.existsSync(REPORT_DIR)) {
    fs.mkdirSync(REPORT_DIR, { recursive: true });
  }
}

/** Format a table row for markdown */
function tableRow(cells: string[]): string {
  return `| ${cells.join(' | ')} |`;
}

/** Format date for non-technical report */
function formatDate(isoString: string): string {
  const date = new Date(isoString);
  return date.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
}

/** Generate the technical markdown report */
function generateTechnicalReport(summary: TestRunSummary): string {
  const lines: string[] = [];

  lines.push('# API Integration Report');
  lines.push('');
  lines.push(`**Run Date:** ${summary.runDate}`);
  lines.push(`**Duration:** ${summary.durationMs}ms`);
  lines.push('');

  const expectedCount = summary.expected.length;
  const unexpectedCount = summary.unexpected.length;
  const timeoutCount = summary.timeout.length;

  lines.push('## Summary');
  lines.push('');
  lines.push('| ✅ Expected | ❌ Unexpected | ⚠️ Timeout |');
  lines.push('|-------------|---------------|------------|');
  lines.push(`| ${expectedCount} | ${unexpectedCount} | ${timeoutCount} |`);
  lines.push('');

  if (summary.expected.length > 0) {
    lines.push('## ✅ Expected Results');
    lines.push('');
    lines.push('Tests that behaved as designed (valid inputs accepted, invalid inputs rejected).');
    lines.push('');
    lines.push(tableRow(['Test', 'EP Class', 'Polarity', 'Expected', 'Actual', 'Latency']));
    lines.push(tableRow(['----', '--------', '--------', '--------', '------', '-------']));

    for (const r of summary.expected) {
      lines.push(
        tableRow([
          r.description.slice(0, 50),
          r.equivalenceClass,
          r.polarity,
          String(r.expectedStatus),
          String(r.actualStatus),
          `${r.latencyMs}ms`,
        ]),
      );
    }
    lines.push('');
  }

  if (summary.unexpected.length > 0) {
    lines.push('## ❌ Unexpected Results');
    lines.push('');
    lines.push('Tests where API behaviour did not match expectations.');
    lines.push('');
    lines.push(tableRow(['Test', 'EP Class', 'Polarity', 'Expected', 'Actual', 'Error']));
    lines.push(tableRow(['----', '--------', '--------', '--------', '------', '-----']));

    for (const r of summary.unexpected) {
      lines.push(
        tableRow([
          r.description.slice(0, 50),
          r.equivalenceClass,
          r.polarity,
          String(r.expectedStatus),
          String(r.actualStatus),
          r.error?.slice(0, 30) ?? 'Status mismatch',
        ]),
      );
    }
    lines.push('');
  }

  if (summary.timeout.length > 0) {
    lines.push('## ⚠️ Timeout / Inconclusive');
    lines.push('');
    lines.push(
      'Tests that failed due to network issues, timeouts, or other infrastructure problems.',
    );
    lines.push('');
    lines.push(tableRow(['Test', 'EP Class', 'Error']));
    lines.push(tableRow(['----', '--------', '-----']));

    for (const r of summary.timeout) {
      lines.push(
        tableRow([
          r.description.slice(0, 50),
          r.equivalenceClass,
          r.error?.slice(0, 50) ?? 'Timeout',
        ]),
      );
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by QA-Automation-Suites integration reporter*');

  return lines.join('\n');
}

/** Generate the non-technical stakeholder summary */
function generateStakeholderSummary(summary: TestRunSummary): string {
  const lines: string[] = [];

  const expectedCount = summary.expected.length;
  const unexpectedCount = summary.unexpected.length;
  const timeoutCount = summary.timeout.length;
  const totalTests = summary.totalTests;

  const allPassed = unexpectedCount === 0 && timeoutCount === 0;
  const hasIssues = unexpectedCount > 0;
  const hasTimeouts = timeoutCount > 0;

  // Determine overall status
  let statusEmoji: string;
  let statusText: string;

  if (allPassed) {
    statusEmoji = '✅';
    statusText = 'All checks passed';
  } else if (hasIssues) {
    statusEmoji = '❌';
    statusText = `${unexpectedCount} issue${unexpectedCount > 1 ? 's' : ''} found`;
  } else {
    statusEmoji = '⚠️';
    statusText = 'Completed with warnings';
  }

  lines.push('# API Integration Summary');
  lines.push('');
  lines.push(`**Date:** ${formatDate(summary.runDate)}`);
  lines.push('**System:** ParaBank API — Accounts Service');
  lines.push(`**Result:** ${statusEmoji} ${statusText}`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## What was tested');
  lines.push('');
  lines.push('We verified that the banking system correctly handles account lookups:');
  lines.push('');
  lines.push(
    `- ${expectedCount > 0 ? '✅' : '❌'} **Valid requests** — Can customers retrieve their account information?`,
  );
  lines.push(
    `- ${summary.expected.some((r) => r.polarity === 'negative') ? '✅' : '❌'} **Invalid requests** — Does the system reject bad or malformed data?`,
  );
  lines.push(
    `- ${summary.expected.some((r) => r.equivalenceClass.startsWith('boundary')) ? '✅' : '❌'} **Edge cases** — Are unusual inputs handled safely?`,
  );
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Results at a glance');
  lines.push('');
  lines.push('| Area | Tests | Status |');
  lines.push('|------|-------|--------|');

  // Group by category for summary
  const validTests = summary.expected.filter((r) => r.polarity === 'positive').length;
  const invalidTests = summary.expected.filter(
    (r) => r.polarity === 'negative' && !r.equivalenceClass.startsWith('boundary'),
  ).length;
  const boundaryTests = summary.expected.filter((r) =>
    r.equivalenceClass.startsWith('boundary'),
  ).length;

  lines.push(`| Normal usage | ${validTests} | ${validTests > 0 ? '✅ Working' : '❌ Issues'} |`);
  lines.push(
    `| Error handling | ${invalidTests} | ${invalidTests > 0 ? '✅ Working' : '⚠️ Not tested'} |`,
  );
  lines.push(
    `| Edge cases | ${boundaryTests} | ${boundaryTests > 0 ? '✅ Working' : '⚠️ Not tested'} |`,
  );
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## What this means');
  lines.push('');

  if (allPassed) {
    lines.push(
      'The account lookup service is functioning correctly. Users can access their accounts, and the system properly rejects invalid requests without exposing errors or sensitive information.',
    );
  } else if (hasIssues) {
    lines.push(
      'Some tests did not behave as expected. This may indicate a bug or a change in API behaviour that needs investigation.',
    );
    lines.push('');
    lines.push('**Issues found:**');
    for (const r of summary.unexpected) {
      lines.push(`- ${r.description}`);
    }
  } else if (hasTimeouts) {
    lines.push(
      'All functional tests passed, but some tests could not complete due to network or infrastructure issues. These should be re-run to confirm.',
    );
  }

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Next steps');
  lines.push('');

  if (allPassed) {
    lines.push('- No action required');
  } else if (hasIssues) {
    lines.push('- Review unexpected results with development team');
    lines.push('- Check if API behaviour has intentionally changed');
  } else {
    lines.push('- Re-run tests to confirm timeout issues');
    lines.push('- Check network/infrastructure if timeouts persist');
  }

  lines.push('- Full technical details available in `integration-report.md`');
  lines.push('');
  lines.push('---');
  lines.push('*Generated by QA-Automation-Suites*');

  return lines.join('\n');
}

/** Write all report files */
function writeIntegrationReport(summary: TestRunSummary): void {
  ensureReportDir();

  // Technical report (devs)
  const technical = generateTechnicalReport(summary);
  fs.writeFileSync(INTEGRATION_REPORT_FILE, technical, 'utf8');

  // Stakeholder summary (non-technical)
  const stakeholder = generateStakeholderSummary(summary);
  fs.writeFileSync(INTEGRATION_SUMMARY_FILE, stakeholder, 'utf8');

  // JSON for machines / CI artifacts
  fs.writeFileSync(INTEGRATION_JSON_FILE, JSON.stringify(summary, null, 2), 'utf8');

  console.log(`\n📊 Reports written to:`);
  console.log(`   - ${INTEGRATION_REPORT_FILE}`);
  console.log(`   - ${INTEGRATION_SUMMARY_FILE}`);
  console.log(`   - ${INTEGRATION_JSON_FILE}`);
}

export { writeIntegrationReport, generateTechnicalReport, generateStakeholderSummary, REPORT_DIR };
export type { TestResultRecord, TestRunSummary };
